curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Francois_Hollande_2015.jpeg/64px-Francois_Hollande_2015.jpeg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg/64px-Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Albert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg/64px-Albert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/SchwarzeneggerJan2010.jpg/64px-SchwarzeneggerJan2010.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Goethe_%28Stieler_1828%29.jpg/64px-Goethe_%28Stieler_1828%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Sigmund_Freud_LIFE.jpg/64px-Sigmund_Freud_LIFE.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/John_Major_2014.jpg/64px-John_Major_2014.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Official_Portrait_of_President_Reagan_1981.jpg/64px-Official_Portrait_of_President_Reagan_1981.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Abraham_Lincoln_November_1863.jpg/64px-Abraham_Lincoln_November_1863.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/64px-Nietzsche187a.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Valls_Toulouse_2012.JPG/64px-Valls_Toulouse_2012.JPG|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Valls_Toulouse_2012.JPG/64px-Valls_Toulouse_2012.JPG|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Margaret_Thatcher.png/64px-Margaret_Thatcher.png|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/David_Cameron_official.jpg/64px-David_Cameron_official.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Salvador_Dali_NYWTS.jpg/64px-Salvador_Dali_NYWTS.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Angela_Merkel_Juli_2010_-_3zu4.jpg/64px-Angela_Merkel_Juli_2010_-_3zu4.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Dalai_Lama_1430_Luca_Galuzzi_2007crop.jpg/64px-Dalai_Lama_1430_Luca_Galuzzi_2007crop.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/14-01-10-tbh-013.jpg/64px-14-01-10-tbh-013.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/ArafatEconomicForum.jpg/64px-ArafatEconomicForum.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/2013-01-20-niedersachsenwahl-002.jpg/64px-2013-01-20-niedersachsenwahl-002.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/John_F_Kennedy.jpg/64px-John_F_Kennedy.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Pele200802FabioRodriguesPozzebomAgenciaBrasil.jpg/64px-Pele200802FabioRodriguesPozzebomAgenciaBrasil.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Michelle_Obama_2013_official_portrait.jpg/64px-Michelle_Obama_2013_official_portrait.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Konfuzius-1770.jpg/64px-Konfuzius-1770.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/David_Lynch_%28cropped_edit%29.jpg/64px-David_Lynch_%28cropped_edit%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Stefan_Raab-2.jpg/64px-Stefan_Raab-2.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheHigh.jpg/64px-CheHigh.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Biden_2013.jpg/64px-Biden_2013.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Lenin_in_Switzerland.jpg/64px-Lenin_in_Switzerland.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Madonna_La_Vie_en_rose.jpg/64px-Madonna_La_Vie_en_rose.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/William_Shatner_at_Comic-Con_2012_cropped.jpg/64px-William_Shatner_at_Comic-Con_2012_cropped.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Kofi_Annan_2012_%28cropped%29.jpg/64px-Kofi_Annan_2012_%28cropped%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Xi_Jinping_October_2013_%28cropped%29.jpg/64px-Xi_Jinping_October_2013_%28cropped%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Bundesarchiv_Bild_183-1986-0421-044%2C_Berlin%2C_XI._SED-Parteitag%2C_Erich_Honecker.jpg/64px-Bundesarchiv_Bild_183-1986-0421-044%2C_Berlin%2C_XI._SED-Parteitag%2C_Erich_Honecker.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Noam_Chomsky_portrait_2015.jpg/64px-Noam_Chomsky_portrait_2015.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/MotherTeresa_094.jpg/64px-MotherTeresa_094.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Elvis_Presley_1970.jpg/64px-Elvis_Presley_1970.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Bill_Clinton_portrait_%282015%29.jpg/64px-Bill_Clinton_portrait_%282015%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Paolo_Monti_-_Servizio_fotografico_%28Milano%2C_1953%29_-_BEIC_6356204.jpg/64px-Paolo_Monti_-_Servizio_fotografico_%28Milano%2C_1953%29_-_BEIC_6356204.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/64px-President_Barack_Obama.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Marilyn_Monroe_%281961%29.jpg/64px-Marilyn_Monroe_%281961%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Thomas_Mann_1937.jpg/64px-Thomas_Mann_1937.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/ChuckNorris200611292256.jpg/64px-ChuckNorris200611292256.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Hitchcock%2C_Alfred_02.jpg/64px-Hitchcock%2C_Alfred_02.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Sir_Winston_S_Churchill.jpg/64px-Sir_Winston_S_Churchill.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Alan_Turing_Aged_16.jpg/64px-Alan_Turing_Aged_16.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/G%C3%BCnter_Grass%2C_2004.jpg/64px-G%C3%BCnter_Grass%2C_2004.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Joachim_L%C3%B6w%2C_Germany_national_football_team_%2805%29.jpg/64px-Joachim_L%C3%B6w%2C_Germany_national_football_team_%2805%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Le_Pen%2C_Marine-9586.jpg/64px-Le_Pen%2C_Marine-9586.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Vincent_van_Gogh_-_Self-portrait_with_grey_felt_hat_-_Google_Art_Project.jpg/64px-Vincent_van_Gogh_-_Self-portrait_with_grey_felt_hat_-_Google_Art_Project.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/MartinLuther-workshopCranachElder.jpg/64px-MartinLuther-workshopCranachElder.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Gerhard_Schr%C3%B6der_%28cropped%29.jpg/64px-Gerhard_Schr%C3%B6der_%28cropped%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/TomHanksJan2009.jpg/64px-TomHanksJan2009.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Elton_John_2011_Shankbone_2.JPG/64px-Elton_John_2011_Shankbone_2.JPG|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Portrait_Gandhi.jpg/64px-Portrait_Gandhi.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/64px-Albert_Einstein_Head.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Karl_Marx_001.jpg/64px-Karl_Marx_001.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Paul_McCartney_black_and_white_2010.jpg/64px-Paul_McCartney_black_and_white_2010.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/John_McCain_official_portrait_2009.jpg/64px-John_McCain_official_portrait_2009.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Jimmy_Wales_Fundraiser_Appeal.JPG/64px-Jimmy_Wales_Fundraiser_Appeal.JPG|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Henry_Kissinger.jpg/64px-Henry_Kissinger.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/General_Charles_de_Gaulle_in_1945.jpg/64px-General_Charles_de_Gaulle_in_1945.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Reagan_Mitterrand_1984_%28cropped%29.jpg/64px-Reagan_Mitterrand_1984_%28cropped%29.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Usain_Bolt_Rio_100m_final_2016k.jpg/64px-Usain_Bolt_Rio_100m_final_2016k.jpg|wc
curl https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Ban_Ki-moon_1-2.jpg/64px-Ban_Ki-moon_1-2.jpg|wc





