curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/rancois_Hollande_2015.jpeg/64px-rancois_Hollande_2015.jpeg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpeg,
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/rida_Kahlo%2C_by_Guillermo_Kahlo.jpg/64px-rida_Kahlo%2C_by_Guillermo_Kahlo.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/lbert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg/64px-lbert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/chwarzeneggerJan2010.jpg/64px-chwarzeneggerJan2010.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/oethe_%28Stieler_1828%29.jpg/64px-oethe_%28Stieler_1828%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/igmund_Freud_LIFE.jpg/64px-igmund_Freud_LIFE.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/ohn_Major_2014.jpg/64px-ohn_Major_2014.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/fficial_Portrait_of_President_Reagan_1981.jpg/64px-fficial_Portrait_of_President_Reagan_1981.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/braham_Lincoln_November_1863.jpg/64px-braham_Lincoln_November_1863.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/ietzsche187a.jpg/64px-ietzsche187a.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/alls_Toulouse_2012.JPG/64px-alls_Toulouse_2012.JPG > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..JPG
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/argaret_Thatcher.png/64px-argaret_Thatcher.png > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..png
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/avid_Cameron_official.jpg/64px-avid_Cameron_official.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/alvador_Dali_NYWTS.jpg/64px-alvador_Dali_NYWTS.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/ngela_Merkel_Juli_2010_-_3zu4.jpg/64px-ngela_Merkel_Juli_2010_-_3zu4.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/alai_Lama_1430_Luca_Galuzzi_2007crop.jpg/64px-alai_Lama_1430_Luca_Galuzzi_2007crop.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/4-01-10-tbh-013.jpg/64px-4-01-10-tbh-013.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/rafatEconomicForum.jpg/64px-rafatEconomicForum.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/013-01-20-niedersachsenwahl-002.jpg/64px-013-01-20-niedersachsenwahl-002.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/ohn_F_Kennedy.jpg/64px-ohn_F_Kennedy.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/ele200802FabioRodriguesPozzebomAgenciaBrasil.jpg/64px-ele200802FabioRodriguesPozzebomAgenciaBrasil.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/ichelle_Obama_2013_official_portrait.jpg/64px-ichelle_Obama_2013_official_portrait.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/onfuzius-1770.jpg/64px-onfuzius-1770.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/avid_Lynch_%28cropped_edit%29.jpg/64px-avid_Lynch_%28cropped_edit%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/tefan_Raab-2.jpg/64px-tefan_Raab-2.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/heHigh.jpg/64px-heHigh.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/iden_2013.jpg/64px-iden_2013.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/enin_in_Switzerland.jpg/64px-enin_in_Switzerland.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/adonna_La_Vie_en_rose.jpg/64px-adonna_La_Vie_en_rose.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/illiam_Shatner_at_Comic-Con_2012_cropped.jpg/64px-illiam_Shatner_at_Comic-Con_2012_cropped.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/ofi_Annan_2012_%28cropped%29.jpg/64px-ofi_Annan_2012_%28cropped%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/i_Jinping_October_2013_%28cropped%29.jpg/64px-i_Jinping_October_2013_%28cropped%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/undesarchiv_Bild_183-1986-0421-044%2C_Berlin%2C_XI._SED-Parteitag%2C_Erich_Honecker.jpg/64px-undesarchiv_Bild_183-1986-0421-044%2C_Berlin%2C_XI._SED-Parteitag%2C_Erich_Honecker.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/oam_Chomsky_portrait_2015.jpg/64px-oam_Chomsky_portrait_2015.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/otherTeresa_094.jpg/64px-otherTeresa_094.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/lvis_Presley_1970.jpg/64px-lvis_Presley_1970.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/ill_Clinton_portrait_%282015%29.jpg/64px-ill_Clinton_portrait_%282015%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/aolo_Monti_-_Servizio_fotografico_%28Milano%2C_1953%29_-_BEIC_6356204.jpg/64px-aolo_Monti_-_Servizio_fotografico_%28Milano%2C_1953%29_-_BEIC_6356204.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/resident_Barack_Obama.jpg/64px-resident_Barack_Obama.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/arilyn_Monroe_%281961%29.jpg/64px-arilyn_Monroe_%281961%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/homas_Mann_1937.jpg/64px-homas_Mann_1937.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/huckNorris200611292256.jpg/64px-huckNorris200611292256.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/itchcock%2C_Alfred_02.jpg/64px-itchcock%2C_Alfred_02.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/ir_Winston_S_Churchill.jpg/64px-ir_Winston_S_Churchill.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/lan_Turing_Aged_16.jpg/64px-lan_Turing_Aged_16.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/%C3%BCnter_Grass%2C_2004.jpg/64px-%C3%BCnter_Grass%2C_2004.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/oachim_L%C3%B6w%2C_Germany_national_football_team_%2805%29.jpg/64px-oachim_L%C3%B6w%2C_Germany_national_football_team_%2805%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/e_Pen%2C_Marine-9586.jpg/64px-e_Pen%2C_Marine-9586.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/incent_van_Gogh_-_Self-portrait_with_grey_felt_hat_-_Google_Art_Project.jpg/64px-incent_van_Gogh_-_Self-portrait_with_grey_felt_hat_-_Google_Art_Project.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/artinLuther-workshopCranachElder.jpg/64px-artinLuther-workshopCranachElder.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/erhard_Schr%C3%B6der_%28cropped%29.jpg/64px-erhard_Schr%C3%B6der_%28cropped%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/omHanksJan2009.jpg/64px-omHanksJan2009.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/lton_John_2011_Shankbone_2.JPG/64px-lton_John_2011_Shankbone_2.JPG > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..JPG
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/ortrait_Gandhi.jpg/64px-ortrait_Gandhi.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/lbert_Einstein_Head.jpg/64px-lbert_Einstein_Head.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/arl_Marx_001.jpg/64px-arl_Marx_001.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/aul_McCartney_black_and_white_2010.jpg/64px-aul_McCartney_black_and_white_2010.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/ohn_McCain_official_portrait_2009.jpg/64px-ohn_McCain_official_portrait_2009.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/immy_Wales_Fundraiser_Appeal.JPG/64px-immy_Wales_Fundraiser_Appeal.JPG > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..JPG
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/enry_Kissinger.jpg/64px-enry_Kissinger.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/eneral_Charles_de_Gaulle_in_1945.jpg/64px-eneral_Charles_de_Gaulle_in_1945.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/eagan_Mitterrand_1984_%28cropped%29.jpg/64px-eagan_Mitterrand_1984_%28cropped%29.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/sain_Bolt_Rio_100m_final_2016k.jpg/64px-sain_Bolt_Rio_100m_final_2016k.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
curl https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/an_Ki-moon_1-2.jpg/64px-an_Ki-moon_1-2.jpg > tpic;a=`sha256sum tpic`;b=${a:0:64};mv tpic p/$b..jpg
